### ISSUE TITLE
Use ES6 modules and tree shaking

### ISSUE THREAD

**Issue by bates64** [programdothouse/editor#12]
[Rollupify](https://github.com/nolanlawson/rollupify) allows us to tree-shake JavaScript, which basically means that unused functions are not included in the build. This means smaller file sizes.

Rollup, however, requires the use of ES6 modules over `require`:
```js
import { coolFn } from './util'
```

Problem is, [parcel doesn't yet support ES6 module syntax](https://github.com/nathan/parcel/issues/9) due to its complexity. We could:
* **Ditch parcel.** This would likely result in longer development build times, but we'd be able to use Rollup.
* **Contribute to parcel** and attempt to add ES6 module support upstream. This is the best option provided someone has the time to do it.
* **Don't bother.** This would result in a much larger assets/editor.js, which isn't great.

**Comment by PullJosh** [comment]
Is it possible to run Rollupify in production builds only?

**Comment by bates64** [comment]
@PullJosh Yeah, that's what I'm proposing.

Problem is, for development, parcel is unable to parse import/export, and in order to use rollup we need to use import/export - - we'd use browserify in dev too (with less plugins, like how the CSS is processed) but that'd certainly be slower than just using parcel.

Is that a worthwhile tradeoff for significantly smaller production files? I have no idea.
