### ISSUE TITLE
Tutorials/References sidebar resizable?

### ISSUE THREAD

**Issue by towerofnix** [programdothouse/editor#4]
At the moment the splitter between the code area and the result pane is movable. It might be best if there was also a similar splitter between the tutorials/references sidebar; on my screen it fills up more space than the code area!

<img width="1280" alt="Screenshot of editor" src="https://user-images.githubusercontent.com/9948030/28248839-333a0a80-6a19-11e7-94e3-0d8785373cb1.png">

**Comment by bates64** [comment]
We're going to make the help pane be collapsible, similar to how it is in the Scratch editor.

**Comment by towerofnix** [comment]
Sounds good. Makes more sense to not necessarily have it be resizable after reading #11, particularly:

> When you enter a tutorial, the three code panes are replaced with a single article (with paragraphs and other articley things), with editable code boxes embedded inside.
